### ISSUE TITLE
qmdkqmlplay QML example flickering on top of Qt 3D scene

### ISSUE THREAD

**Issue by lukegluke** [wang-bin/mdk-examples#9]
qmdkqmlplay QML example based on QQuickFramebufferObject works fine as itself.

But if MDKPlayer is on top of Qt Scene3D, there is no video rendered or it is flickering in more complex application (it looks like something clearing item after renderVideo is called). Any other QML Quick items on top of Qt Scene3D are ok. Audio is working.
Example based on qmdkqmlplay + [qt3d-scene3d-example](https://doc.qt.io/archives/qt-5.9/qt3d-scene3d-example.html) for test:
[mdk-example.zip](https://github.com/wang-bin/mdk-examples/files/6223016/mdk-example.zip)

If renderPolicy: RenderSettings.OnDemand for Scene3D is set (uncomment the line in code) video stops flickering and get rendered right when 3d scene is still. Start rotate the 3d camera and MDKPlayer start flickering due to Scene3D updates.

Same behavior Windows 10, android armv7
Qt 5.9.5, MinGW 5.3.0 32bit, android SDK 25.2.5, NDK 16.1.44794999

**Comment by wang-bin** [comment]
video在Scene3D下方时可正常。原因还在查

**Comment by wang-bin** [comment]
This change can fix the issue https://github.com/wang-bin/mdk-examples/commit/98567ffcc6129bbd4447b9864ff3501f57fb351b

**Comment by lukegluke** [comment]
Indeed it fixed the issue, @wang-bin, thanks!

Now when I get back to tests, my app on windows crashed after several seconds without starting video. Only when I updated mdk-sdk from 0.10.4 to the newest 0.11.0 it starts working back again. According to mdk-sdk readme I suppose I can use it for free for any purpose without updating, but with an QR image in the last frame. Am I wrong?

**Comment by wang-bin** [comment]
Crash is not expected, and it was fixed recently. The readme says it's free for opensource or non-commercial softwares and i can give you a license key, otherwise you have to [update your sdk every month](https://github.com/wang-bin/appkey/blob/main/app.cpp#L190). btw, qr is only rendered in opengl, so if using d3d, metal or vk renderer via qt rhi you will not see qr

**Comment by lukegluke** [comment]
Thanks for the explanations!

**Comment by lukegluke** [comment]
I have similar to example, but more complex application with Scene3D that previously works with blinking in 0.10.4, but now it crashes on start playing rtsp from local ip camera (it manages to show several frames). BigBuckBunny rtsp [stream ](rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov) from internet works without crashing. The simple example here works fine with local rtsp. How can I debug it?

![изображение](https://user-images.githubusercontent.com/3624285/114313478-619dc680-9aff-11eb-8705-fa26c2f95e03.png)

**Comment by wang-bin** [comment]
Please show me your log, setLogHandler() can redirect the log. qtcreator can debug, ensure mdk.pdb exists

**Comment by lukegluke** [comment]
Here is a [log](https://github.com/wang-bin/mdk-examples/files/6295192/crash_on_rtsp_local_ip_camera.log) with crash. If set log handler and run debug it doesn't crash (but lag a lot).
mdk.pdb file exist near mdk.dll for each architecture, but qt creator doesn't show symbols.
I didn't find in google easily how to add path to .pdb in qt creator for gdb on windows, maybe you can help faster, thanks in advance!

Qt Creator 4.10.2
gdb 7.10.1 for MinGW 5.3.0 32bit

For now no problems on android arm-v7 (despite this general issue https://github.com/wang-bin/mdk-sdk/issues/24)

**Comment by wang-bin** [comment]
gdb does not support pdb files. you have to use  cdb, and msvc toolchain may be required in qtcreator
